"""add updated_by to memories

Revision ID: a752ba7f6e0f
Revises: 354e00693e1a
Create Date: 2026-02-13 11:18:37.511226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a752ba7f6e0f'
down_revision: Union[str, Sequence[str], None] = '354e00693e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite has limited support for ALTER COLUMN.
    # Since we are just adding a column, we can do that safely.
    # The other alterations seem to be type detection noise from Alembic + SQLite + UUIDs.
    # We should only keep the relevant changes.
    
    op.add_column('memories', sa.Column('updated_by', sa.String(), nullable=True))
    
    # We can try to add the index if it doesn't exist, but it's safer to just add the column for now.
    # op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'updated_by')
    # ### end Alembic commands ###
